services:

  mongodb:
    build:
      context: ./mongoDB
      dockerfile: Dockerfile
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: globalMobility
      MONGO_INITDB_DATABASE: ecommerce
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - globalMobilityNetwork

  ecommerce:
    build:
      context: ./ecommerce
      dockerfile: Dockerfile
    container_name: ecommerce
    restart: always
    environment:
      MONGO_URI: mongodb://admin:globalMobility@mongodb:27017
      MONGO_DB_NAME: ecommerce
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - globalMobilityNetwork

volumes:
  mongodb_data:
  mongodb_config:

networks:
  globalMobilityNetwork:
    driver: bridge
