name: Go Quality Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        working-directory: ./ecommerce

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          cache: true

      - name: Verify dependencies
        run: |
          go mod tidy
          go mod verify

      - name: Run tests
        run: go test -v -race ./internal/... ./test/...

      - name: Generate coverage
        run: |
          go test -v -coverprofile=coverage.out ./internal/... ./test/...
          go tool cover -func=coverage.out

      - name: Save coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./ecommerce/coverage.out
          retention-days: 7