name: Go Quality Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  quality:
    name: Quality Checks
    runs-on: ubuntu-latest
    timeout-minutes: 5

    defaults:
      run:
        working-directory: ./ecommerce

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Verify dependencies
        run: |
          go mod download
          go mod verify

      - name: Run tests and coverage
        run: |
          go test -v -race -coverprofile=coverage.out ./internal/... ./test/...
          go tool cover -func=coverage.out

      - name: Run code analysis
        run: |
          go vet ./internal/... ./test/...
          
      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.3"
          install-go: false
          working-directory: ./ecommerce
          min-go-version: "1.20"

      - name: Store coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./ecommerce/coverage.out
          retention-days: 7