name: Audit

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies
      working-directory: ./ecommerce
      run: |
        go mod download
        go mod verify

    - name: Run tests with coverage
      working-directory: ./ecommerce
      run: |
        go test -v -coverprofile=coverage.out ./internal/... ./test/...
        go tool cover -func=coverage.out

    - name: Run vet
      working-directory: ./ecommerce
      run: go vet ./internal/... ./test/...

    - name: Run staticcheck
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2023.1.3"
        install-go: false
        working-directory: ./ecommerce
        min-go-version: "1.20"